### ISSUE TITLE
Got 'list index out of range' error

### ISSUE THREAD

**Issue by KimiWu123** [mczochowski/articles#1]
Hi, 

I ran your `list index out of range.py` with default values and got the error, 
```
Traceback (most recent call last):
  File ".\sharding_attack_probability.py", line 136, in <module>
    num_success = gf_coeffs(n_groups, n_per_group, limit_per_group, total_placed)
  File ".\sharding_attack_probability.py", line 54, in gf_coeffs
    total_placed_coeff = int(comb_coeffs[-(total_placed-1)])
IndexError: list index out of range
```

I changed `t=10000` for getting result quicker, and I found value of `total_placed` is 150 and the length of `comb_coeffs` is 1. I have no clue what happened. Could you help check it? Thanks.

**Comment by KimiWu123** [comment]
It's working if using Python3. Suggest to write it down in README.md.
